# -*- coding: utf-8 -*-
"""Text summarization final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzTR0k9pQu1-ZDzSNGcNoImue0gDGy_W
"""

text = input("Please enter the text : ")
print(text)

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation

stopwords = list(STOP_WORDS)

nlp = spacy.load('en_core_web_sm')

doc = nlp(text)

tokens = [token.text for token in doc]
print(tokens)

punctuation = punctuation + '\n'
punctuation

word_frequencies = {}
for word in doc:
  if word.text.lower() not in stopwords:
    if word.text.lower() not in punctuation:
      if word.text not in word_frequencies.keys():
        word_frequencies[word.text] = 1
      else:
        word_frequencies[word.text] += 1

print(word_frequencies)

max_frequency = max(word_frequencies.values())

max_frequency

for word in word_frequencies.keys():
  word_frequencies[word] = word_frequencies[word]/max_frequency

print(word_frequencies)

sentence_tokens = [sent for sent in doc.sents]
print(sentence_tokens)

sentence_score = {}
for sent in sentence_tokens:
  for word in sent:
    if word.text.lower() in word_frequencies.keys():
      if sent not in sentence_score.keys():
        sentence_score[sent] = word_frequencies[word.text.lower()]
      else:
        sentence_score[sent] += word_frequencies[word.text.lower()]

sentence_score

from heapq import nlargest

select_length = int(len(sentence_tokens)*0.3)
select_length

summary = nlargest(select_length,sentence_score,key=sentence_score.get)

summary

final_summary = [word.text for word in summary]
summary = ' '.join(final_summary)
print(summary)