# -*- coding: utf-8 -*-
"""Query generation final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ElNrj42OKNEmtf-_oyHTkf-R_zwK9OIL
"""

text = input("Please enter the text : ")
print(text)

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation

stopwords = list(STOP_WORDS)

nlp = spacy.load('en_core_web_sm')

doc = nlp(text)

tokens = [token.text for token in doc]
print(tokens)

punctuation = punctuation + '\n'
punctuation

word_frequencies = {}
for word in doc:
  if word.text.lower() not in stopwords:
    if word.text.lower() not in punctuation:
      if word.text not in word_frequencies.keys():
        word_frequencies[word.text] = 1
      else:
        word_frequencies[word.text] += 1

print(word_frequencies)

max_frequency = max(word_frequencies.values())

for word in word_frequencies.keys():
  word_frequencies[word] = word_frequencies[word]/max_frequency

print(word_frequencies)

sorted_word_frequencies = sorted(word_frequencies.items(), key=lambda x: x[1], reverse=True)
top_words = [word[0] for word in sorted_word_frequencies[:5]]
print("Top 5 Queries are :", top_words)